# Generated by Django 5.2.7 on 2025-10-19 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(help_text="AI-generated chapter content")),
                ("word_count", models.PositiveIntegerField(default=0)),
                (
                    "read_time_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Estimated reading time"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generating", "Generating"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["story", "chapter_number"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="stories.chapter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chapter_number",
                    models.PositiveIntegerField(
                        help_text="Which chapter this prompt is for"
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(
                        help_text="What should happen in the next chapter? (max 500 characters)",
                        max_length=500,
                    ),
                ),
                (
                    "vote_count",
                    models.IntegerField(
                        default=0, help_text="Cached vote count for performance"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("voting", "Voting"),
                            ("winner", "Winner"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "voting_ends_at",
                    models.DateTimeField(
                        help_text="When voting closes for this prompt"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-vote_count", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="prompt_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_chapter",
                to="stories.prompt",
            ),
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description of the story premise"
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("fantasy", "Fantasy"),
                            ("scifi", "Science Fiction"),
                            ("romance", "Romance"),
                            ("mystery", "Mystery"),
                            ("thriller", "Thriller"),
                            ("horror", "Horror"),
                            ("adventure", "Adventure"),
                            ("literary", "Literary Fiction"),
                            ("other", "Other"),
                        ],
                        default="fantasy",
                        max_length=20,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="story_covers/"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this story accepting new prompts?"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscribers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subscribed_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="prompt",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompts",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="stories.story",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="prompt",
            unique_together={("story", "chapter_number", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("story", "chapter_number")},
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="stories.prompt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("prompt", "user")},
            },
        ),
    ]
