# Generated by Django 5.2.7 on 2025-10-19 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="is_active",
        ),
        migrations.AddField(
            model_name="story",
            name="status",
            field=models.CharField(
                choices=[
                    ("pitch", "Pitch - Community Voting"),
                    ("active", "Active - Accepting Chapter Prompts"),
                    ("completed", "Completed"),
                    ("paused", "Paused"),
                ],
                default="pitch",
                help_text="Story status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="upvoters",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who upvoted this story pitch",
                related_name="upvoted_stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="votes_needed",
            field=models.PositiveIntegerField(
                default=10, help_text="Votes needed to activate story"
            ),
        ),
    ]
