# Generated by Django 5.2.7 on 2025-10-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0002_remove_story_is_active_story_status_story_upvoters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("zh", "Chinese"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("pt", "Portuguese"),
                    ("ru", "Russian"),
                    ("ar", "Arabic"),
                ],
                default="en",
                help_text="Story language",
                max_length=5,
            ),
        ),
    ]
