# Generated by Django 5.2.7 on 2025-11-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0003_story_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="story_type",
            field=models.CharField(
                choices=[
                    ("collaborative", "Collaborative Story"),
                    ("personal", "Personal Story"),
                ],
                default="collaborative",
                help_text="Type of story",
                max_length=20,
            ),
        ),
    ]
