# Generated by Django 5.2.7 on 2025-11-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0004_story_story_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="characters",
            field=models.TextField(
                blank=True,
                help_text="Main characters (name, role, description, traits)",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="planned_chapters",
            field=models.PositiveIntegerField(
                blank=True, help_text="Estimated total chapters", null=True
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="story_outline",
            field=models.TextField(
                blank=True, help_text="Overall plot structure and major story beats"
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="themes",
            field=models.TextField(blank=True, help_text="Main themes, tone, and mood"),
        ),
        migrations.AddField(
            model_name="story",
            name="world_building",
            field=models.TextField(
                blank=True,
                help_text="Setting, world rules, magic system, technology level, etc.",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="writing_style_notes",
            field=models.TextField(
                blank=True, help_text="Narrative perspective, pacing preferences, tone"
            ),
        ),
    ]
