# Generated by Django 5.2.7 on 2025-11-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0005_story_characters_story_planned_chapters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="prompt_text",
            field=models.TextField(
                help_text="What should happen in the next chapter? (max 3000 characters)",
                max_length=3000,
            ),
        ),
    ]
